; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:main-test]
platform = espressif32
board = esp32-s3-devkitc1-n8r8
framework = arduino
lib_deps = 
	askuric/Simple FOC@^2.3.5
	simplefoc/SimpleFOCDrivers @ ^1.0.8
	fastled/FastLED@^3.10.2
	adafruit/Adafruit HUSB238 Library@^1.0.1
monitor_speed = 5000000
monitor_port = COM14
upload_speed = 5000000
build_src_filter = +<main.cpp>
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DCONFIG_LOG_DEFAULT_LEVEL=5
	-D ARDUINO_USB_CDC_ON_BOOT=1
	
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
debug_tool = esp-builtin

[env:SimpleFoc-Studio]
platform = espressif32
board = esp32-s3-devkitc1-n8r8
framework = arduino
lib_deps = 
	askuric/Simple FOC@^2.3.5
	simplefoc/SimpleFOCDrivers @ ^1.0.8
	fastled/FastLED@^3.10.2
	adafruit/Adafruit HUSB238 Library@^1.0.1
monitor_speed = 5000000
monitor_port = COM14
upload_speed = 5000000
build_src_filter = -<main.cpp> +<gui-tuner-mode.cpp>
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DCONFIG_LOG_DEFAULT_LEVEL=5
	-D ARDUINO_USB_CDC_ON_BOOT=1
	
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
debug_tool = esp-builtin

[env:TWAI-Test]
platform = espressif32
board = esp32-s3-devkitc1-n8r8
framework = arduino
lib_deps = 
	fastled/FastLED@^3.10.2
	adafruit/Adafruit HUSB238 Library@^1.0.1
build_src_filter = -<main.cpp> -<gui-tuner-mode.cpp> +<can_test.cpp>
monitor_speed = 5000000
monitor_port = COM14
upload_speed = 5000000
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DCONFIG_LOG_DEFAULT_LEVEL=5
	-D ARDUINO_USB_CDC_ON_BOOT=1
	
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1

[env:i2c-scan]
platform = espressif32
board = esp32-s3-devkitc1-n8r8
framework = arduino
lib_deps = 
	fastled/FastLED@^3.10.2
	askuric/Simple FOC@^2.3.5
	simplefoc/SimpleFOCDrivers @ ^1.0.8
	adafruit/Adafruit HUSB238 Library@^1.0.1
build_src_filter = -<main.cpp> -<gui-tuner-mode.cpp> -<usb-pd-can-feature-test.cpp> +<i2c-scan.cpp>
monitor_speed = 5000000
monitor_port = COM14
upload_speed = 5000000
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DCONFIG_LOG_DEFAULT_LEVEL=5
	-D ARDUINO_USB_CDC_ON_BOOT=1
	
	
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1

[env:usb-full-feature-test]
platform = espressif32
board = esp32-s3-devkitc1-n8r8
framework = arduino
lib_deps = 
	fastled/FastLED@^3.10.2
	askuric/Simple FOC@^2.3.5
	simplefoc/SimpleFOCDrivers @ ^1.0.8
	adafruit/Adafruit HUSB238 Library@^1.0.1
build_src_filter = -<main.cpp> -<gui-tuner-mode.cpp> +<usb-pd-can-feature-test.cpp> -<i2c-scan.cpp>
monitor_speed = 5000000
upload_speed = 5000000
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_LOG_DEFAULT_LEVEL=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
