; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:driver]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.filesystem = spiffs
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB
framework = arduino
lib_deps =
	askuric/Simple Foc
	simplefoc/SimpleFOCDrivers
	fastled/FastLED@^3.10.2
monitor_speed = 115200
upload_speed = 5000000
build_src_filter = +<main.cpp>
build_flags =
	-DCORE_DEBUG_LEVEL=3
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D SIMPLEFOC_ESP32_USELEDC

[env:SimpleFoc-Studio]
platform = espressif32
board = seeed_xiao_esp32s3
board_build.filesystem = spiffs
board_build.partitions = partitions.csv
framework = arduino
debug_init_break = tbreak main
lib_deps = 
	askuric/Simple Foc
	simplefoc/SimpleFOCDrivers
	fastled/FastLED@^3.10.2
	adafruit/Adafruit HUSB238 Library@^1.0.1
monitor_speed = 5000000
monitor_port = COM14
upload_speed = 5000000
build_src_filter = -<main.cpp> +<gui-tuner-mode.cpp>
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DCONFIG_LOG_DEFAULT_LEVEL=5
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
debug_tool = esp-builtin

[env:leader]
platform = espressif32
board = seeed_xiao_esp32s3
board_build.filesystem = spiffs
board_build.partitions = partitions.csv
framework = arduino
debug_init_break = tbreak main
lib_deps = 
	; askuric/Simple Foc
	; simplefoc/SimpleFOCDrivers
	fastled/FastLED@^3.10.2
	adafruit/Adafruit HUSB238 Library@^1.0.1
monitor_speed = 5000000
upload_speed = 5000000
build_src_filter = -<main.cpp> +<lead_servo.cpp>
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DCONFIG_LOG_DEFAULT_LEVEL=5
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
debug_tool = esp-builtin

[env:follower]
platform = espressif32
platform_packages =
    tool-xtensa-esp-elf-gdb@~11.2.0
board = seeed_xiao_esp32s3
board_build.filesystem = spiffs
board_build.partitions = partitions.csv
framework = arduino
debug_init_break = tbreak main
lib_deps = 
	; askuric/Simple Foc
	; simplefoc/SimpleFOCDrivers
	fastled/FastLED@^3.10.2
	adafruit/Adafruit HUSB238 Library@^1.0.1
monitor_speed = 5000000
upload_speed = 5000000
build_src_filter = -<main.cpp> +<follow_servo.cpp>
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DCONFIG_LOG_DEFAULT_LEVEL=5
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
	-DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
	-DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
debug_tool = esp-builtin